Helm refresh on charts when repo has synced
SUSE/stratos pull request #338
Opened 2020-02-24 16:29 UTC by nwmac

2020-02-25 14:19 UTC, richard-cox requested changes
Two minor comments, otherwise LGTM

2020-02-25 14:19 UTC, richard-cox commented on custom-src/frontend/app/custom/helm/store/helm.effects.ts
> +        if (endpoint.cnsi_type === 'helm' && endpoint.endpoint_metadata) {
This should probably be `HELM_ENDPOINT_TYPE`

2020-02-25 14:19 UTC, richard-cox commented on custom-src/frontend/app/custom/helm/store/helm.effects.ts
> +      params: null
Should this be `this.syncing`?

2020-02-26 10:17 UTC, nwmac commented on custom-src/frontend/app/custom/helm/store/helm.effects.ts
> +      params: null
Discussed with Richard and leave as is

2020-02-26 15:28 UTC, merged