Add support for a Kubernetes Terminal
SUSE/stratos pull request #384
Opened 2020-06-04 12:51 UTC by nwmac

2020-06-24 14:00 UTC, richard-cox requested changes
See comments

2020-06-24 14:00 UTC, richard-cox commented on deploy/containers/kube-terminal/Dockerfile.kubeterminal
> +FROM splatform/stratos-base:leap15_1
Should this be different for downstream?

2020-06-24 14:00 UTC, richard-cox commented on deploy/containers/kube-terminal/kubeconsole.bashrc
> +  # If env var K8S_VERSION is set, then use it (major.minor only)
Where's K8S_VERSION set?

2020-06-24 14:00 UTC, richard-cox commented on src/jetstream/plugins/kubernetes/terminal/cleanup.go
> +				log.Debug("Kube Terminal Cleanup: Could not get secrets")
Should these err handlers be `log.Debug`?

2020-06-24 14:00 UTC, richard-cox commented on src/jetstream/plugins/kubernetes/terminal/start.go
> +	// This dialer does not use the kubeHttpClient  - is it unused?
Is this a todo?

2020-06-26 13:09 UTC, richard-cox reviewed
Two more comments

2020-06-26 13:09 UTC, richard-cox commented on src/jetstream/plugins/kubernetes/terminal/cleanup.go
> +	wait := rand.Intn(30)
For dev purposes, could we print this out to log.dev?

2020-06-26 13:09 UTC, richard-cox commented on src/jetstream/plugins/kubernetes/terminal/cleanup.go
> +					if sessionID, ok := pod.Annotations["stratos-session"]; ok {
Could this be from `stratosSessionAnnotation`?

2020-06-26 13:33 UTC, nwmac commented on deploy/containers/kube-terminal/Dockerfile.kubeterminal
> +FROM splatform/stratos-base:leap15_1
This is patched at build time.

2020-06-26 13:34 UTC, nwmac commented on deploy/containers/kube-terminal/kubeconsole.bashrc
> +  # If env var K8S_VERSION is set, then use it (major.minor only)
This is injected into the container when the pod is created

2020-06-26 13:38 UTC, nwmac commented on src/jetstream/plugins/kubernetes/terminal/start.go
> +	// This dialer does not use the kubeHttpClient  - is it unused?
I think I cleaned that up - I have now removed the comment.

2020-06-26 13:39 UTC, nwmac commented on src/jetstream/plugins/kubernetes/terminal/cleanup.go
> +	wait := rand.Intn(30)
Done

2020-06-26 13:40 UTC, nwmac commented on src/jetstream/plugins/kubernetes/terminal/cleanup.go
> +				log.Debug("Kube Terminal Cleanup: Could not get secrets")
Change to warn

2020-06-26 13:40 UTC, nwmac commented on src/jetstream/plugins/kubernetes/terminal/cleanup.go
> +					if sessionID, ok := pod.Annotations["stratos-session"]; ok {
Yes - I've fixed

2020-06-26 14:01 UTC, richard-cox approved these changes
LGTM, will merge once passed gates

2020-06-26 15:13 UTC, merged