Security observability
SUSE/stratos pull request #398
Opened 2020-06-24 11:57 UTC by nwmac

2020-06-30 10:55 UTC, richard-cox requested changes
I've jumped the gun a bit and gone through the frontend code (backend it's probably better for you to talk through). Added comments to https://github.com/SUSE/stratos/issues/401 also.

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/core/src/shared/components/cards/card-number-metric/card-number-metric.component.theme.scss
> +      background-color: red;
We've got some status colours that would be good to use here
```
  $status-colors: map-get($app-theme, status);
  $status-success: map-get($status-colors, success);
  $status-warning: map-get($status-colors, warning);
  $status-danger: map-get($status-colors, danger);
  $status-tentative: map-get($status-colors, tentative);
  $status-info: map-get($status-colors, info);
```

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/kubernetes-entity-factory.ts
> +  { idAttribute: (entity) => entity.id }
This can be just `{ idAttribute: 'id' }`

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/kubernetes-resource-viewer/kubernetes-resource-viewer.component.ts
> +    this.analysis = props.analysis;
This is probably a v2 thing, but would be cool to tie this into the pods lists as well.
- They should all use a common base config service (`BaseKubernetesPodsListConfigService`)
- Would need an extra column to show some kind of summary state
- Would need `analysis` property passed through in name cell's cellConfig 
- The overlay enable/selection drop down integration might be tricky. Maybe the kube analysis service could store this and be provided/have an instance per place it's used?

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/list-types/analysis-reports-list-config.service.ts
> +      console.log(item);
console.log (there's a few dotted around)

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/list-types/analysis-reports-list-source.ts
> +    const action = new GetAnalysisReports(endpointService.baseKube.guid);
This i guess should be action builder'ed. Also the endpoint guid is being ignored

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/list-types/analysis-reports-list-source.ts
> +      getRowUniqueId: (entity: AnalysisReport) => entity.id,
For consistency this can be grabbed from the schema in the action

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/services/kubernetes.analysis.service.ts
> +      this.store.dispatch(new ClearPaginationOfType(action));
I _think_ the `ResetPagination` action should work better here, think that's the one that retains user filter/sort choices

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/services/kubernetes.analysis.service.ts
> +    this.store.dispatch(new ClearPaginationOfType(action));
Same action could be used here

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/services/kubernetes.analysis.service.ts
> +      const ref = this.snackBar.open(msg, 'View', { duration: 5000 });
This should use the snackbar service

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/services/kubernetes.analysis.service.ts
> +        console.log('Do not know how to handle this report type');
This should be console.warning or similar, same with all error handling in this service

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/store/kubernetes.effects.ts
> +        .pipe(mergeMap(response => {
This needs a `catchError` which returns a `WrapperRequestActionFailed`

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/tabs/kubernetes-analysis-tab/kubernetes-analysis-info/analysis-info-card/analysis-info-card.component.ts
> +    this.renderer.link = (href, title, text) => `<a target="_blank" title="${title}" href="${href}">${text}</a>`;
This title is `null`

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-resource-graph/helm-release-resource-graph.component.html
> +  <app-analysis-report-selector *ngIf="analyzerService.enabled$ | async" (selected)="analysisChanged($event)" [endpoint]="helper.endpointGuid" [path]="path"></app-analysis-report-selector>
This doesn't show the analysis reports for me. Selecting 'none' throws 
```
core.js:6228 ERROR TypeError: ctx_r3.analysisChanged is not a function
    at HelmReleaseResourceGraphComponent_app_analysis_report_selector_6_Template_app_analysis_report_selector_selected_0_listener (helm-release-resource-graph.component.html:7)
```

2020-06-30 10:55 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-resource-graph/helm-release-resource-graph.component.ts
> +      // if (!this.didInitialFit) {
Comments

2020-07-10 12:31 UTC, nwmac commented on deploy/kubernetes/console/values.yaml
> +  analyzers: stratos-analyzers
Remove

2020-07-10 12:33 UTC, nwmac commented on deploy/kubernetes/console/values.yaml
> +  analyzers: stratos-analyzers
or use a default

2020-07-10 12:42 UTC, nwmac commented on src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.ts
> +    ).pipe(map(([tabNav, tabSubNav, tabSubNavBreadcrumb]) => [tabNav ? tabNav.label : null, tabSubNav, tabNav, tabSubNavBreadcrumb]));
Get rid of data[2] and always return [tabNav, tabSubNav, tabSubNavBreadcrumb]

2020-07-10 13:00 UTC, nwmac commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/analysis-report-viewer/analysis-report-selector/analysis-report-selector.component.html
> +  <!-- Note - it would be good to only show if there's no reports `*ngIf="analyzers.length > 0"`. However this causes
Create an issue for this @richard-cox

2020-07-10 13:03 UTC, nwmac commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/analysis-report-viewer/analysis-report-viewer.component.ts
> +  set report(report: any) {
Add typing

2020-07-23 16:33 UTC, richard-cox reviewed
see comments

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/container/kubescore.go
> +	log.Error(scriptPath)
Could be debug

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/container/kubescore.go
> +	args := []string{scriptPath, job.KuebConfigPath, job.Config.Namespace}
`KuebConfigPath` typo

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/container/kubescore.go
> +			reportFile := filepath.Join(job.Folder, "repor.log")
`repor.log`

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/container/kubescore.go
> +			reportFile := filepath.Join(job.Folder, "repor.log")
CI - When out of tech preview - clean old copies

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/container/popeye.go
> +	log.Warn("Path is %s", job.Path)
log.Warn & others

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/container/routes.go
> +		log.Warnf("Could not delete Analysis report folder: %s", folder)
Return err or log text to user. Same below

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/container/run.go
> +		log.Error("Error running analyzer: %s", err)
Add `job.Status = "error"`

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/container/status.go
> +			log.Errorf("Removing job >>>> %s", id)
log.Errorf

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/main.go
> +	log.Info("Analysis plugin loaded")
Gate on tech preview (check other plugins). Check with line 94

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/run.go
> +		report.Status = "error"
report.Status here and line 170 not needed

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/run.go
> +	defer rsp.Body.Close()
Confirm when this should be called (only if ReadAll?)

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/run.go
> +func getScriptFolder() string {
Is this still needed?

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/status.go
> +		log.Infof("Got running job: %s", job.ID)
should be debug

2020-07-23 16:33 UTC, richard-cox commented on src/jetstream/plugins/analysis/status.go
> +		}
Review clean up process. Add else case, mark job as error (in db, but not in container)?

2020-07-24 08:25 UTC, richard-cox commented on src/jetstream/plugins/kubernetes/helm/release.go
> +	fe, _ := os.Create("/home/nwm/manifest_err.yaml")
Debug code

2020-07-24 14:23 UTC, richard-cox approved these changes

2020-07-24 14:23 UTC, merged