Show caasp node versions and indicate if nodes have updates available
SUSE/stratos pull request #451
Opened 2020-08-19 12:42 UTC by nwmac

fixes #450

2020-08-20 15:43 UTC, richard-cox requested changes
I made a couple of tweaks whilst reviewing
- securityUpdates looks at `CAASP_SECURITY_UPDATES_ANNOTATION` value
- fixed a typo in a function name

There's one question inline regarding behaviour on missing annotations

I think we should also add it to the below places as well. The user will want to investigate and find which nodes have the issues. If so I can have a look in a separate PR?
- conditionally add info in the nodes list if the endpoint type is caasp
- add the info to the node summary page

2020-08-20 15:43 UTC, richard-cox commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/services/kubernetes-endpoint.service.ts
> +    return annotations[annotation] && annotations[annotation] === 'no' ? 0 : 1
I tried this with a node that only had the caasp version annotation and it came up with 1 node needing upgrade with a disruptive and a security update. In cases where it's missing should this return 0?

2020-08-21 09:54 UTC, nwmac commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/services/kubernetes-endpoint.service.ts
> +    return annotations[annotation] && annotations[annotation] === 'no' ? 0 : 1
Logic broken

2020-08-21 09:57 UTC, nwmac commented on src/frontend/packages/suse-extensions/src/custom/kubernetes/services/kubernetes-endpoint.service.ts
> +    return annotations[annotation] && annotations[annotation] === 'no' ? 0 : 1
return !annotations[annotation] || annotations[annotation] && annotations[annotation] === 'no' ? 0 : 1

2020-08-27 14:35 UTC, merged